language: node_js
node_js:
  - 14

services:
  - postgresql
  
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_fruit_baskets_app

before_script:
  - psql -c 'create database  my_fruit_baskets_app' -U postgres
  - psql -U postgres -d my_fruit_baskets_app -a -f sql/create-table.sql
  - psql -U postgres -d my_fruit_baskets_app -a -f sql/insert-data.sql